imports:
    - { resource: config.yml }

doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver:
                    cache_provider: pim
                result_cache_driver:
                    cache_provider: pim
                query_cache_driver:
                    cache_provider: pim

oro_assetic:
    css_debug:      ~
    css_debug_all:  false
